In [1]:
# import libraries 
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [43]:
orders_products_merged_customers = pd.read_pickle(r'C:\Users\alexg\InstacartBasketAnalysis\02Data\PreparedData\orders_products_merged_customers.pkl')

In [ ]:
orders_products_merged_customers[:1000000]

MemoryError:

In [56]:
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [ ]:
orders_products_merged_customers['price_range'] = orders_products_merged_customers.apply(price_label, axis=1)

In [58]:
orders_products_merged_customers['price_range'].value_counts(dropna = False)

KeyError: 'price_range'

In [44]:
orders_products_merged_customers['max_order'] = orders_products_merged_customers.groupby(['user_id'])['order_number'].transform(np.max)

In [45]:
orders_products_merged_customers.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,first_name,last_name,gender,state,age,date_joined,dependants,marital_status,income,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
2,907,Premium Sliced Bacon,106,12,20.0,3160996,138,1,5,13,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
3,907,Premium Sliced Bacon,106,12,20.0,2254091,138,10,5,14,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
4,1000,Apricots,18,10,12.9,505689,138,9,6,12,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
5,3265,Mini Seedless Watermelon Pack,32,4,1.7,960220,138,17,5,14,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
6,4913,Table Water Crackers,78,19,4.4,894221,138,23,5,13,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
7,6184,Clementines,32,4,4.3,1977647,138,30,6,17,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
8,6901,Raisin Bran,121,14,2.9,1154289,138,18,1,7,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
9,7147,Classic Baby Creamers Potatoes,83,4,9.0,930730,138,2,0,12,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
10,7987,Hazelnut Spread with Cocoa,88,13,12.8,1592314,138,5,0,9,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
11,8048,Packaged Grape Tomatoes,32,4,11.4,930730,138,2,0,12,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
12,8048,Packaged Grape Tomatoes,32,4,11.4,1421595,138,3,2,9,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
13,10473,Half And Half Cream,53,16,7.0,3160996,138,1,5,13,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32
14,10473,Half And Half Cream,53,16,7.0,930730,138,2,0,12,...,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620,32

In [46]:
orders_products_merged_customers.loc[orders_products_merged_customers['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [47]:
orders_products_merged_customers.loc[(orders_products_merged_customers['max_order'] <= 40) & (orders_products_merged_customers['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [48]:
orders_products_merged_customers.loc[orders_products_merged_customers['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [49]:
orders_products_merged_customers['prices'].value_counts(dropna = False)

12.3       624300
10.3       510496
4.0        447272
6.3        438467
1.3        425691
7.3        411924
8.2        404015
1.4        392209
6.7        379126
4.5        367223
4.4        357026
6.8        355246
14.3       348208
7.9        342988
13.2       333183
5.7        323997
1.8        321184
9.1        320782
4.9        318220
8.8        318091
3.8        315426
6.9        314196
14.0       311640
12.8       309727
11.4       303015
3.6        300127
1.6        299352
2.0        286259
11.8       284495
5.3        284243
7.0        282884
14.7       279291
6.5        278357
8.3        276230
4.1        268269
2.9        264700
1.2        256276
8.6        254009
3.2        253782
5.2        251509
5.5        250136
3.1        249256
2.5        246421
4.2        245755
6.1        244209
1.1        242782
2.3        242051
5.8        241047
7.5        239261
14.1       238211
3.3        238041
10.5       237657
7.4        233506
9.0        228576
8.4        227493
5.0        225904
13.4       225857
11.5       225399
5.1        224797
3.4        223571
7.2        223120
3.5        222786
3.7        222159
4.7        221048
8.9        219412
9.6        216626
13.5       216276
1.7        213967
11.3       212926
3.9        212805
11.2       212323
2.6        211936
5.9        208900
5.4        206769
6.4        206468
11.7       206199
2.1        206004
6.6        204936
10.6       204804
2.7        199785
9.4        197179
6.0        196985
2.4        196042
12.2       194980
9.8        194754
4.8        193898
3.0        192650
10.7       191705
7.7        190070
14.8       188865
7.8        186923
5.6        183638
11.0       183505
9.2        182444
12.1       182165
13.7       181882
6.2        178656
8.1        176805
12.6       174427
13.3       173797
13.6       172962
11.1       169709
9.9        169263
9.3        168917
14.4       168344
8.7        166742
10.2       165789
9.5        165789
10.9       165607
12.0       164717
13.8       162616
4.3        162367
12.9       160860
2.2        160243
14.9       156433
1.9        156179
1.5        154527
2.8        153979
12.5       152781
8.0        151542
11.6       148742
13.9       145234
4.6        144069
7.1        140813
14.6       139880
10.1       139263
8.5        139244
10.4       133058
14.5       131344
10.0       127842
11.9       127349
12.7       124544
14.2       121003
9.7        120777
13.1       117052
1.0        115143
13.0       114503
7.6        113878
12.4        97895
15.0        97261
10.8        94286
21.1        33805
19.6        28383
22.3        19430
24.2        15891
18.2        14923
23.2        14866
25.0        13772
23.8        12585
21.6        10598
18.7        10503
23.1         9135
23.6         8458
18.6         8451
18.1         8027
21.3         7647
15.3         7495
24.7         7283
20.7         6568
19.3         6537
24.9         5781
20.0         5775
19.7         5538
19.4         5457
20.4         5351
22.1         5204
15.9         5078
16.9         4971
23.3         4803
16.8         4795
15.7         4551
14900.0      4429
18.8         4363
24.0         4327
17.3         4309
17.1         4231
16.6         4212
16.4         3892
22.9         3884
17.0         3836
20.1         3745
23.0         3265
18.5         3105
16.7         3105
19.1         2926
24.3         2889
19.0         2823
21.7         2553
16.5         2541
15.1         2422
15.5         2325
22.6         2275
24.5         2148
23.9         2074
17.7         2073
24.6         1962
23.5         1924
16.2         1823
18.4         1762
17.4         1721
16.1         1622
23.7         1346
22.4         1280
16.0         1272
22.0         1182
22.2         1178
15.4         1175
20.6         1167
18.0         1135
22.8         1089
20.9         1079
17.2         1001
17.8          981
19.2          981
24.1          978
20.5          945
19.9          887
20.8          852
15.8          772
22.5          706
99999.0       698
21.9          689
17.6          640
21.8          546
24.4          499
15.2          494
18.9          483
19.5          453
24.8          410
17.5          369
23.4          368
19.8          344
15.6          333
16.3          287
20.3          236
17.9          137
21.4          137
20.2          123
22.7           99
21.5           85
18.3           11
21.0            8
Name: prices, dtype: int64

In [50]:
orders_products_merged_customers['loyalty_flag'].value_counts(dropna = False)

Regular customer    15891077
Loyal customer      10293737
New customer         6249398
Name: loyalty_flag, dtype: int64

In [37]:
pd.options.display.max_rows = None

In [51]:
orders_products_merged_customers[['user_id', 'loyalty_flag', 'prices']].head(100)

   user_id      loyalty_flag  prices
0      138  Regular customer     5.8
1      138  Regular customer     5.8
2      138  Regular customer    20.0
3      138  Regular customer    20.0
4      138  Regular customer    12.9
5      138  Regular customer     1.7
6      138  Regular customer     4.4
7      138  Regular customer     4.3
8      138  Regular customer     2.9
9      138  Regular customer     9.0
10     138  Regular customer    12.8
11     138  Regular customer    11.4
12     138  Regular customer    11.4
13     138  Regular customer     7.0
14     138  Regular customer     7.0
15     138  Regular customer     7.0
16     138  Regular customer     7.0
17     138  Regular customer     7.0
18     138  Regular customer     7.0
19     138  Regular customer     7.0
20     138  Regular customer     7.0
21     138  Regular customer     7.0
22     138  Regular customer     7.0
23     138  Regular customer     7.0
24     138  Regular customer     7.0
25     138  Regular customer     7.0
26     138  Regular customer     7.0
27     138  Regular customer     7.0
28     138  Regular customer     7.0
29     138  Regular customer     7.0
30     138  Regular customer     4.4
31     138  Regular customer     9.1
32     138  Regular customer     9.1
33     138  Regular customer     9.1
34     138  Regular customer     9.1
35     138  Regular customer     9.1
36     138  Regular customer     9.1
37     138  Regular customer     9.1
38     138  Regular customer     9.1
39     138  Regular customer     9.1
40     138  Regular customer     4.9
41     138  Regular customer     4.2
42     138  Regular customer     3.9
43     138  Regular customer     3.9
44     138  Regular customer    12.0
45     138  Regular customer    12.0
46     138  Regular customer    12.0
47     138  Regular customer     1.8
48     138  Regular customer     9.3
49     138  Regular customer     9.3
50     138  Regular customer     5.1
51     138  Regular customer     5.1
52     138  Regular customer     5.1
53     138  Regular customer     5.1
54     138  Regular customer     5.1
55     138  Regular customer     5.1
56     138  Regular customer     5.1
57     138  Regular customer     5.1
58     138  Regular customer     5.1
59     138  Regular customer    12.1
60     138  Regular customer    11.7
61     138  Regular customer    11.7
62     138  Regular customer     1.4
63     138  Regular customer     1.4
64     138  Regular customer     1.4
65     138  Regular customer     1.4
66     138  Regular customer     1.4
67     138  Regular customer    13.6
68     138  Regular customer    13.6
69     138  Regular customer    13.6
70     138  Regular customer    13.6
71     138  Regular customer     8.2
72     138  Regular customer    14.0
73     138  Regular customer    14.0
74     138  Regular customer    14.0
75     138  Regular customer    14.0
76     138  Regular customer    14.0
77     138  Regular customer    14.0
78     138  Regular customer    14.0
79     138  Regular customer    14.0
80     138  Regular customer    14.0
81     138  Regular customer    14.0
82     138  Regular customer     1.6
83     138  Regular customer     5.1
84     138  Regular customer     5.1
85     138  Regular customer     5.1
86     138  Regular customer     5.1
87     138  Regular customer    12.7
88     138  Regular customer    12.7
89     138  Regular customer     2.0
90     138  Regular customer    15.0
91     138  Regular customer     3.0
92     138  Regular customer     3.0
93     138  Regular customer     4.5
94     138  Regular customer    13.7
95     138  Regular customer     5.9
96     138  Regular customer     3.2
97     138  Regular customer     5.4
98     138  Regular customer     6.6
99     138  Regular customer     6.6

In [62]:
orders_products_merged_customers['prices'] = orders_products_merged_customers.groupby(['max_order'])['user_id'].transform(np.max)

In [61]:
orders_products_merged_customers['prices'].dtype

dtype('O')

In [54]:
orders_products_merged_customers['max_order'].dtype

dtype('int64')

In [55]:
orders_products_merged_customers['user_id'].dtype

dtype('O')

In [40]:
orders_products_merged_customers.loc[(orders_products_merged_customers['prices'] >= 10) & (orders_products_merged_customers['prices'] > 10), 'big_spender_flag'] = 'High spender'

TypeError: '>=' not supported between instances of 'str' and 'int'

In [15]:
orders_products_merged_customers.loc[orders_products_merged_customers['prices'] <= 10, 'big_spender_flag'] = 'Low spender'

TypeError: '<=' not supported between instances of 'str' and 'int'

In [16]:
orders_products_merged

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434207,49688,Fresh Foaming Cleanser,73,11,13.5,1788356,200215,2,0,9,5.0,27,0,both
32434208,49688,Fresh Foaming Cleanser,73,11,13.5,3401313,200377,1,4,11,NaN,5,0,both
32434209,49688,Fresh Foaming Cleanser,73,11,13.5,809510,200873,5,3,8,15.0,12,0,both
32434210,49688,Fresh Foaming Cleanser,73,11,13.5,2359893,200873,9,3,15,5.0,11,1,both
32434211,49688,Fresh Foaming Cleanser,73,11,13.5,2385091,205926,11,1,15,6.0,35,0,both

In [17]:
path = r'C:\Users\alexg\InstacartBasketAnalysis'

In [18]:
orders_products_merged.to_csv(os.path.join(path, '02Data', 'PreparedData', 'orders_products_merged.csv'))

In [19]:
orders_products_merged.to_pickle(os.path.join(path, '02Data', 'PreparedData', 'orders_products_merged.pkl'))

In [27]:
orders_products_merged_customers = orders_products_merged.merge(df_customers_checked, on = 'user_id')

In [29]:
orders_products_merged_customers[:2000000]

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,Unnamed: 0,first_name,last_name,gender,state,age,date_joined,dependants,marital_status,income
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,163461,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,163461,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620
2,907,Premium Sliced Bacon,106,12,20.0,3160996,138,1,5,13,...,163461,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620
3,907,Premium Sliced Bacon,106,12,20.0,2254091,138,10,5,14,...,163461,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620
4,1000,Apricots,18,10,12.9,505689,138,9,6,12,...,163461,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,12935,Organic Pasture Raised Brown Eggs,86,16,13.3,1922864,146163,8,5,9,...,68655,Judy,Lucas,Female,Washington,58,1/31/2018,0,single,159343
1999996,12935,Organic Pasture Raised Brown Eggs,86,16,13.3,2756317,146163,10,6,8,...,68655,Judy,Lucas,Female,Washington,58,1/31/2018,0,single,159343
1999997,12935,Organic Pasture Raised Brown Eggs,86,16,13.3,339334,146163,12,1,14,...,68655,Judy,Lucas,Female,Washington,58,1/31/2018,0,single,159343
1999998,12935,Organic Pasture Raised Brown Eggs,86,16,13.3,1085977,146163,13,5,12,...,68655,Judy,Lucas,Female,Washington,58,1/31/2018,0,single,159343
1999999,12935,Organic Pasture Raised Brown Eggs,86,16,13.3,849312,146163,14,5,9,...,68655,Judy,Lucas,Female,Washington,58,1/31/2018,0,single,159343

In [31]:
orders_products_merged_customers.columns

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices',
       'order_id', 'user_id', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_prior_order', 'add_to_cart_order',
       'reordered', '_merge', 'Unnamed: 0', 'first_name', 'last_name',
       'gender', 'state', 'age', 'date_joined', 'dependants', 'marital_status',
       'income'],
      dtype='object')

In [35]:
orders_products_merged_customers.to_pickle(os.path.join(path, '02Data', 'PreparedData', 'orders_products_merged_customers.pkl'))

In [ ]:
orders_products_merged_customers.to_csv(os.path.join(path, '02Data', 'PreparedData', 'orders_products_merged_customers.csv'))

up

In [6]:
crosstab = pd.crosstab(ords_prods_merge['days_since_prior_order'], ords_prods_merge['order_number'], dropna = False)

In [7]:
crosstab.to_clipboard()

In [8]:
ords_prods_merge.columns

Index(['Unnamed: 0', 'product_id', 'product_name', 'aisle_id', 'department_id',
       'prices', 'order_id', 'user_id', 'eval_set', 'order_number',
       'orders_day_of_the_week', 'busiest_hours_of_the_day',
       'days_since_prior_order', 'add_to_cart_order', 'reordered', '_merge',
       'price_range', 'price_range_loc', 'busiest_day', 'busiest_days',
       'max_order', 'loyalty_flag', 'big_spender_flag', 'frequency_flag'],
      dtype='object')

In [9]:
ords_prods_merge

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,...,reordered,_merge,price_range,price_range_loc,busiest_day,busiest_days,max_order,loyalty_flag,big_spender_flag,frequency_flag
0,0,1,Chocolate Sandwich Cookies,61,19,205273,3139998,138,prior,28,...,0,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,205273,Regular customer,High spender,Non-frequent customer
1,1,1,Chocolate Sandwich Cookies,61,19,205273,1977647,138,prior,30,...,1,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,205273,Regular customer,High spender,Non-frequent customer
2,2,1,Chocolate Sandwich Cookies,61,19,205273,389851,709,prior,2,...,0,both,Mid-range product,Mid-range product,Busiest day,Busiest days,205273,New customer,High spender,Non-frequent customer
3,3,1,Chocolate Sandwich Cookies,61,19,205273,652770,764,prior,1,...,0,both,Mid-range product,Mid-range product,Regularly busy,Least busy,205273,New customer,High spender,Non-frequent customer
4,4,1,Chocolate Sandwich Cookies,61,19,205273,1813452,764,prior,3,...,1,both,Mid-range product,Mid-range product,Least busy,Regularly busy,205273,New customer,High spender,Non-frequent customer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,28,Wheat Chex Cereal,121,14,36936,1400457,36059,prior,1,...,0,both,Mid-range product,Mid-range product,Busiest day,Busiest days,36936,New customer,High spender,Non-frequent customer
9996,9996,28,Wheat Chex Cereal,121,14,36936,1576558,36936,prior,1,...,0,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,36936,New customer,High spender,Non-frequent customer
9997,9997,28,Wheat Chex Cereal,121,14,36936,2516651,36936,prior,2,...,1,both,Mid-range product,Mid-range product,Busiest day,Busiest days,36936,New customer,High spender,Non-frequent customer
9998,9998,28,Wheat Chex Cereal,121,14,36936,2995837,36936,prior,3,...,1,both,Mid-range product,Mid-range product,Busiest day,Busiest days,36936,New customer,High spender,Non-frequent customer
9999,9999,28,Wheat Chex Cereal,121,14,36936,2522453,36936,prior,4,...,1,both,Mid-range product,Mid-range product,Busiest day,Busiest days,36936,New customer,High spender,Non-frequent customer